version: 2.1
setup: true
orbs:
  path-filtering: circleci/path-filtering@0.0.2
workflows:
  setup:
    jobs:
      - path-filtering/filter:
          base-revision: circleci
          mapping: |
            starlix-infra/starlix-infra.yaml infra-modified true
            starlix-frontend/.* frontend-modified true
            starlix-service/.* service-modified true
          config-path: .circleci/workflows.yml

