name: Automerge

on:
  workflow_dispatch:
  schedule:
    # You can setup schedule here
    - cron: '0 9 * * 5'

jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge master -> /deployment/weekly
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          target_branch: /deployment/weekly
          github_token: ${{ github.token }}
