name: Automerge

on:
  schedule:
    # You can setup schedule here
    - cron: '*/5 13 * * *'

jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Merge main -> deployment/weekly
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          target_branch: deployment/weekly
          github_token: ${{ github.token }}
